Categories:
  - Internet
License: GPL-2.0-or-later
AuthorName: MoltenStar
WebSite: https://moltenstar.space
SourceCode: https://github.com/MoltenSt4r/MoltenGram
IssueTracker: https://github.com/MoltenSt4r/MoltenGram/issues
Name: MoltenGram
AutoName: MoltenGram
Summary: Modern Material Design 3 Telegram Client
Description: |-
  MoltenGram is an experimental Telegram client fork based on exteraless and NagramX.
  Features full Material You / Monet support, 10 unique launcher icons, Chaquopy Python plugin engine, and modern UI.

AutoUpdateMode: None
UpdateCheckMode: Static
CurrentVersion: 12.10.6
CurrentVersionCode: 1261
