name: Publish Existing Build

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: 'Run ID to publish'
        required: true

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact from previous run
        uses: actions/download-artifact@v4
        with:
          name: Release
          run-id: ${{ inputs.run_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path: apk_release

      - name: Inspect downloaded files
        run: |
          ls -la apk_release/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v12.10.3
          name: ExteraMS v12.10.3
          make_latest: true
          body: |
            ### Релиз ExteraMS v12.10.3
            - Официальный релиз ExteraMS на базе Telegram 12.10.3.
          files: apk_release/*.apk
